### PR TITLE
ADDED 'global' MODIFIER FOR FUNCTION REFERENCES TO GLOBAL CONFIG

### PR DESCRIPTION
**Pull request by BourgeoisBear**
VARIABLES IN functions.php AND phpweather.php (TO RESOLVE WARNINGS IN
PHP 5.5)

### CODE REVIEW

**Comment by benscanfiles** [comment]
Why was this never merged?

**Comment by BourgeoisBear** [comment]
I don’t believe I have permission to merge into your project.



Sincerely,





Jason Stewart

Eggplant Systems and Design <http://www.eggplantsd.com/>

251.366.6428



*From:* benscanfiles [mailto:notifications@github.com]
*Sent:* Monday, December 28, 2015 3:34 PM
*To:* andrew867/timeclock
*Cc:* Jason Stewart
*Subject:* Re: [timeclock] ADDED 'global' MODIFIER FOR FUNCTION REFERENCES
TO GLOBAL CONFIG (#15)



Why was this never merged?

—
Reply to this email directly or view it on GitHub
<https://github.com/andrew867/timeclock/pull/15#issuecomment-167662107>.

**Comment by benscanfiles** [comment]
This isn't my project. I'm asking @andrew867 , why this was never merged :-/

Edit: I've forked it and added all of the fixes that I have found so far to my fork: 
https://github.com/benscanfiles/timeclock

If my company starts using this full time, I'll probably do a proper UI revamp at some point to bring it into this decade :-)

**Comment by andrew867** [comment]
@benscanfiles Seems like I forgot to merge the pull request ;) If you can push back any fixes to this repo in the form of a pull request(s) I'll try my best to keep merging them, unless of course you'd like to have permission to modify this repo directly.

**Comment by benscanfiles** [comment]
@andrew867 my fork contains some pretty important fixes that really should be merged into the master. I've submitted a pull request already.

---
I have a potentially serious blocking bug, and that is that reports ignore the local timezone and are always in GMT. Dealing with date/time functions in php is not one of my stronger areas and I really need some help in fixing it. Even with using the server time, and client offset time, time displayed on reports AND on the main home screen are always in GMT. I have checked the cookie and have verified that it has the correct offset (-480 GMT-8).
---

I will put that in a different issue.

https://github.com/andrew867/timeclock/issues/17

I'm rather happy that you're still around. I'm rather desperately hoping that you can help me with this issue. I can do some really cool stuff to this and bill it to company time if my company actually starts using this as our time clock, but I have to make sure that little tiny things like this don't happen.

**Pull request merged**
