### PR TITLE
Regex update to timadd.php and some other updates to allow remote logos

### PR DESCRIPTION
**Pull request by Nexis81**
I was getting errors with trying to add time. iIt wouldn't let me enter the date. There was a problem with the regex code.

I wasn't able to use a logo from a remote site so modified the topmain.php file to allow it.

Added a target for the leftmain.php link list so links open in new tabs.

### CODE REVIEW

**Comment by andrew867** [comment]
When you changed `../$logo` to `$logo` in `/reports/topmain.php` is there anywhere else in the code that this needs to be changed?

This change in `$logo` should be made everywhere and noted in the config file, ie:

```
/* A logo or graphic, this is displayed in the top left of each page.
   Set it to "none" to ignore this option. */
$logo = "images/logos/phptimeclock.png";
```

Should be changed to:

```
/* A logo or graphic, this is displayed in the top left of each page.
   Set it to "none" to ignore this option. 
   This can either be a relative path (from the root directory) or URL.
*/
$logo = "/images/logos/phptimeclock.png";
```

**Comment by benscanfiles** [comment]
Wrt the logo, that's a curious assumption to use ../$logo

All looks good. I'm not in a position to where I can grep for $logo, but assuming that's the only place that it needs changed, looks solid to me :-)

**Comment by Nexis81** [comment]
I didn't see anywhere else it needs to be changed other than the topmain.php files.

**Comment by benscanfiles** [comment]
Excellent, Thanks! :-)

**Pull request merged**
